version: "3.9"

services:
  api:
    build:
      context: api
      dockerfile: ${PWD}/.docker/django/Dockerfile
    volumes:
      - ./api:/home/django/app/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:14.1-alpine
    volumes:
      - .docker/db/data:/var/run/postgresql/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - "${SQL_PORT}:5432"
    restart: unless-stopped
  
  web:
    build:
      context: web
      dockerfile: ${PWD}/.docker/node/Dockerfile
    command: pm2 serve dist/ 8000 --name 'ecommerce' --spa --no-daemon
    ports:
      - "3030:8000"
    restart: unless-stopped
  
  nginx:
    build:
      context: .docker/nginx
      dockerfile: ${PWD}/.docker/nginx/Dockerfile

volumes:
  postgres_data:
