version: "3.9"

services:
  api:
    build:
      context: api
      dockerfile: ${PWD}/.docker/django/Dockerfile
    volumes:
      - ./api:/home/django/app/
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    network_mode: host

  db:
    image: postgres:14.1-alpine
    volumes:
      - .docker/db/data:/var/run/postgresql/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    network_mode: host
    restart: unless-stopped

  web:
    build:
      context: web
      dockerfile: ${PWD}/.docker/node/Dockerfile
    restart: unless-stopped
    command: pm2 serve dist/ 3030 --name 'ecommerce' --spa --no-daemon
    network_mode: host

  nginx:
    build:
      context: .docker/nginx
      dockerfile: ${PWD}/.docker/nginx/Dockerfile
    network_mode: bridge

volumes:
  postgres_data:
