version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - .docker/db/data:/var/run/postgresql/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    restart: unless-stopped

  api:
    build:
      context: api
      dockerfile: ${PWD}/.docker/django/Dockerfile
    volumes:
      - ./api:/home/django/app/
    env_file:
      - .env
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000

  web:
    build:
      context: web
      dockerfile: ${PWD}/.docker/node/Dockerfile
    volumes:
      - ./web:/app
    restart: unless-stopped
    command: yarn dev -- --host
    depends_on:
      - api
    ports:
      - 3000:3000

volumes:
  postgres_data:
