name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create environment files
        run: sh create-env-file.sh

      - name: Build Docker image
        run: |
          docker-compose build

  test-api:
    runs-on: self-hosted
    depends: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Django API Test
        run: |
          docker-compose run api python manage.py test

  test-web:
    runs-on: self-hosted
    needs: [build, test-api]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Django API Test
        run: |
          docker-compose run web yarn test

  deploy:
    runs-on: self-hosted
    needs: [build, test-api, test-web]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start/Reload pm2
        run: |
          docker-compose up -d
